<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJMhuZE7\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJMhuZE7/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJMhuZE7.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJMhuZE7\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJMhuZE7\appAppKernelProdContainer([
    'container.build_hash' => 'JMhuZE7',
    'container.build_id' => '7b3fef77',
    'container.build_time' => 1741680105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJMhuZE7');
